# Copyright (c) 2020, Xgrid Solutions Ltd, https://xgrid.co
#
# This source is subject to the Xgrid License.
# All rights reserved.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF
# ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
#
# Xgrid confidential information, delete if you are not the
# intended recipient.
CommitMsg:
  GerritChangeId:
    enabled: true
    description: 'Ensure Gerrit Change-Id is present'
    required: true
  RussianNovel:
    enabled: true
    description: 'Check length of commit message'
    quiet: true
  SingleLineSubject:
    enabled: true
    description: 'Check subject line'
  TextWidth:
    enabled: true
    description: 'Check text width'
    max_subject_width: 60
    max_body_width: 72
  TrailingPeriod:
    enabled: true
    description: 'Check for trailing periods in subject'
PreCommit:
  EsLint:
    enabled: true
    description: 'Analyze with Eslint'
    required_executable: 'eslint'
    install_command: 'npm install -g eslint eslint-config-airbnb-base eslint-plugin-import'
    include:
      - '**/*.js'
      - '**/*.jsx'
    exclude:
      - '**/node_modules/*'
    command: ['eslint', '--ext', '.jsx', '--ext', 'js', '.']
    on_warn: pass
  JsHint:
    enabled: false
    description: 'Analyze with JSHint'
    required_executable: 'jshint'
    flags: ['--verbose']
    install_command: 'npm install -g jshint'
    include: '**/*.js'
  CssLint:
    enabled: false
    description: 'Analyze with csslint'
    required_executable: 'csslint'
    flags: ['--quiet', '--format=compact']
    install_command: 'npm install -g csslint'
    include: '**/*.css'
  HtmlTidy:
    enabled: false
    description: 'Analyze HTML with tidy'
    required_executable: 'tidy'
    flags: ['-errors', '-quiet', '-utf8']
    include: '**/*.html'
  JsonSyntax:
    enabled: true
    description: 'Validate JSON syntax'
    required_library: 'json'
    install_command: 'gem install json'
    include: '**/*.json'
  HardTabs:
    enabled: true
    description: 'Check for hard tabs'
    quiet: true
    required_executable: 'grep'
    flags: ['-IHn', "\t"]
  MergeConflicts:
    enabled: true
    description: 'Check for merge conflicts'
    quiet: true
    required_executable: 'grep'
    flags: ['-IHn', "^<<<<<<<[ \t]"]
  TrailingWhitespace:
    enabled: true
    description: 'Check for trailing whitespace'
    required_executable: 'grep'
    flags: ['-IHn', "[ \t]$"]